# Import needed Libraries

- numpy : martixes and calculation
- pandas : data manipulation and representation (.csv fies)
- random : randomizing
- math

In [1]:
import numpy as np
import pandas as pn
import random as rand
import math
# import networkx as nx
# import matplotlib.pyplot as plt

# Bring me data

Import data from a .csv file that contains 20 Sudoku tables extracted from 'qqwing.com/generate.html'

In [2]:
df = pn.read_csv('../docs/sample.csv')
df[['Puzzle', 'Difficulty']].head()

Puzzle Difficulty
0  .59..27..........51.7..5......3....691..67.......     Expert
1  ...4..3...6...1.7.4.1....5...8...7....52...1.6...     Expert
2  ...6.....6....2...4.2.57...7.9.6.4..5....93.22...       Easy
3  .71.6......38.....2.4.93..........86.6.91.3..8...     Expert
4  .7.6.24.3.......56..2.1.....2...9.6.3..1.....7...     Expert

# Selection
Select one of 'em randomly

It can be selected depends on 'Difficulty'(optional)

In [3]:
col1 = df['Puzzle'][rand.randint(0, 19)]

In [4]:
# Declare matrix dimation
num = 0
for char in col1:
    num += 1

dim = int(math.sqrt(num))

# Result

And now we have a nparray, that represents a specific Sudoku table with specifc dificulty.

**The 0 cells, consider as empty**.

In [5]:
# Convert the string to a list of integers
col1 = col1.replace('.', '0')
numbers = [int(x) for x in col1]

# Creating the 2D matrix
matrix = [numbers[i * dim:(i + 1) * dim] for i in range(dim)]

numpy_array = np.array(matrix)
numpy_array

array([[5, 8, 0, 0, 0, 0, 7, 0, 0],
       [0, 7, 0, 0, 0, 1, 4, 0, 5],
       [0, 0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 3, 5, 0],
       [8, 5, 3, 0, 0, 0, 0, 1, 4],
       [0, 0, 0, 0, 0, 4, 0, 0, 3],
       [0, 0, 4, 0, 2, 8, 5, 7, 0],
       [0, 0, 0, 0, 0, 7, 8, 0, 0]])

In [9]:
# Initialize an empty list to store the submatrices
Blocks = []

# Split the matrix into 3x3 blocks
for i in range(3):
    for j in range(3):
        Block = numpy_array[i*3:(i+1)*3, j*3:(j+1)*3]
        Blocks.append(Block)

# Print the resulting submatrices
for idx, Block in enumerate(Blocks):
    print(f"Block {idx+1}:\n{Block}\n")


Submatrix 1:
[[5 8 0]
 [0 7 0]
 [0 0 0]]

Submatrix 2:
[[0 0 0]
 [0 0 1]
 [6 0 0]]

Submatrix 3:
[[7 0 0]
 [4 0 5]
 [0 0 0]]

Submatrix 4:
[[0 0 1]
 [0 6 0]
 [8 5 3]]

Submatrix 5:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Submatrix 6:
[[0 0 0]
 [3 5 0]
 [0 1 4]]

Submatrix 7:
[[0 0 0]
 [0 0 4]
 [0 0 0]]

Submatrix 8:
[[0 0 4]
 [0 2 8]
 [0 0 7]]

Submatrix 9:
[[0 0 3]
 [5 7 0]
 [8 0 0]]



# Functions

Here we have a Function, (i would like to call it the *Harrass Function*) called **is_treated()** checks if we a value can be sited in a cell or not (depends on row and column).

The function helps us with BFS algorithm, when a branch has noting to offer (not promising in other hand).

In [7]:
def is_treated(matrix, pos, value):
    
    #Checks if there's any same value in row or column
    if value in matrix[pos[0]] or value in matrix.T[pos[1]]:
        return False
    else:
        return True

In [8]:
is_treated(numpy_array, [0, 3], 6)

False

# All you have to do is:

Implanting BackTrack alg and run it on this matrix

Another file i created called 'Visual.ipynb' can be use for visualisition using networks library