# Import needed Libraries

- numpy : martixes and calculation
- pandas : data manipulation and representation (.csv fies)
- random : randomizing
- math

In [1]:
import numpy as np
import pandas as pn
import random as rand
import math
# import networkx as nx
# import matplotlib.pyplot as plt

# Bring me data

Import data from a .csv file that contains 20 Sudoku tables extracted from 'qqwing.com/generate.html'

In [2]:
df = pn.read_csv('../docs/sample.csv')
df[['Puzzle', 'Difficulty']].head()

Puzzle Difficulty
0  .59..27..........51.7..5......3....691..67.......     Expert
1  ...4..3...6...1.7.4.1....5...8...7....52...1.6...     Expert
2  ...6.....6....2...4.2.57...7.9.6.4..5....93.22...       Easy
3  .71.6......38.....2.4.93..........86.6.91.3..8...     Expert
4  .7.6.24.3.......56..2.1.....2...9.6.3..1.....7...     Expert

# Selection
Select one of 'em randomly

It can be selected depends on 'Difficulty'(optional)

In [3]:
col1 = df['Puzzle'][rand.randint(0, 19)]

In [4]:
# Declare matrix dimation
num = 0
for char in col1:
    num += 1

dim = int(math.sqrt(num))

# Result

And now we have a nparray, that represents a specific Sudoku table with specifc dificulty.

**The 0 cells, consider as empty**.

In [5]:
# Convert the string to a list of integers
col1 = col1.replace('.', '0')
numbers = [int(x) for x in col1]

# Creating the 2D matrix
matrix = [numbers[i * dim:(i + 1) * dim] for i in range(dim)]

numpy_array = np.array(matrix)
numpy_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 2, 5, 0],
       [5, 0, 0, 0, 0, 0, 6, 8, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 7, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 8, 2, 1, 7, 9],
       [4, 0, 1, 0, 7, 0, 0, 0, 5],
       [0, 0, 7, 0, 9, 0, 0, 0, 0],
       [6, 0, 8, 4, 1, 0, 0, 0, 0]])

In [6]:
# # We have 9 Blocks
# list = [[], [], [], [], [], [], [], [], []]
# Block = []
# m, n = 0, 0

# for i in range(3 * m + 2):
#     for j in range(3 * n + 2):
#         print(numpy_array[i][j])
#         n += 1
#     n = 0
#     m += 1

In [4]:
import numpy as np

# Create a 9x9 matrix (you can replace this with your actual matrix)
matrix = np.arange(81).reshape(9, 9)
print(matrix)
# Split the matrix into 3x3 blocks
blocks = np.split(matrix, 3)
blocks[0]
# Print the resulting blocks
# for block in blocks:
#     print(block)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
# Create a 9x9 square matrix (you can replace this with your actual matrix)
matrix = np.arange(81).reshape(9, 9)
print(matrix)
# Initialize an empty list to store the submatrices
submatrices = []

# Split the matrix into 3x3 blocks
for i in range(3):
    for j in range(3):
        submatrix = matrix[i*3:(i+1)*3, j*3:(j+1)*3]
        submatrices.append(submatrix)

# Print the resulting submatrices
for idx, submatrix in enumerate(submatrices):
    print(f"Submatrix {idx+1}:\n{submatrix}\n")


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
Submatrix 1:
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]

Submatrix 2:
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]

Submatrix 3:
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]

Submatrix 4:
[[27 28 29]
 [36 37 38]
 [45 46 47]]

Submatrix 5:
[[30 31 32]
 [39 40 41]
 [48 49 50]]

Submatrix 6:
[[33 34 35]
 [42 43 44]
 [51 52 53]]

Submatrix 7:
[[54 55 56]
 [63 64 65]
 [72 73 74]]

Submatrix 8:
[[57 58 59]
 [66 67 68]
 [75 76 77]]

Submatrix 9:
[[60 61 62]
 [69 70 71]
 [78 79 80]]



# Functions

Here we have a Function, (i would like to call it the *Harrass Function*) called **is_treated()** checks if we a value can be sited in a cell or not (depends on row and column).

The function helps us with BFS algorithm, when a branch has noting to offer (not promising in other hand).

In [7]:
def is_treated(matrix, pos, value):
    
    #Checks if there's any same value in row or column
    if value in matrix[pos[0]] or value in matrix.T[pos[1]]:
        return False
    else:
        return True

In [8]:
is_treated(numpy_array, [0, 3], 6)

True

# All you have to do is:

Implanting BackTrack alg and run it on this matrix

Another file i created called 'Visual.ipynb' can be use for visualisition using networks library